import type { Account, Transaction } from "./types";

function id(prefix: string, n: number) {
  return `${prefix}-${n}`;
}

export function demoAccounts(): Account[] {
  return [
    { id: "cash", name: "現金", kind: "cash", openingBalance: 12500 },
    { id: "bank", name: "銀行", kind: "bank", openingBalance: 98600 },
    { id: "card", name: "信用卡", kind: "card", openingBalance: -5680 },
  ];
}

export function demoTransactions(month: string): Transaction[] {
  const rows: Array<Omit<Transaction, "id">> = [
    {
      type: "expense",
      categoryId: "housing",
      amount: 18000,
      note: "房租",
      date: `${month}-01`,
      accountId: "bank",
      toAccountId: null,
    },
    {
      type: "income",
      categoryId: "salary",
      amount: 52000,
      note: "八月薪資",
      date: `${month}-05`,
      accountId: "bank",
      toAccountId: null,
    },
    {
      type: "expense",
      categoryId: "food",
      amount: 285,
      note: "咖啡與早餐",
      date: `${month}-06`,
      accountId: "cash",
      toAccountId: null,
    },
    {
      type: "expense",
      categoryId: "food",
      amount: 420,
      note: "午餐",
      date: `${month}-07`,
      accountId: "cash",
      toAccountId: null,
    },
    {
      type: "expense",
      categoryId: "transport",
      amount: 1280,
      note: "悠遊卡儲值",
      date: `${month}-08`,
      accountId: "cash",
      toAccountId: null,
    },
    {
      type: "expense",
      categoryId: "shopping",
      amount: 2400,
      note: "日用品",
      date: `${month}-09`,
      accountId: "cash",
      toAccountId: null,
    },
    {
      type: "expense",
      categoryId: "food",
      amount: 1680,
      note: "超市採買",
      date: `${month}-10`,
      accountId: "card",
      toAccountId: null,
    },
    {
      type: "expense",
      categoryId: "sub",
      amount: 390,
      note: "Netflix",
      date: `${month}-11`,
      accountId: "card",
      toAccountId: null,
    },
    {
      type: "expense",
      categoryId: "food",
      amount: 560,
      note: "晚餐",
      date: `${month}-12`,
      accountId: "cash",
      toAccountId: null,
    },
    {
      type: "expense",
      categoryId: "fun",
      amount: 880,
      note: "電影",
      date: `${month}-14`,
      accountId: "card",
      toAccountId: null,
    },
    {
      type: "income",
      categoryId: "bonus",
      amount: 8000,
      note: "專案獎金",
      date: `${month}-15`,
      accountId: "bank",
      toAccountId: null,
    },
    {
      type: "expense",
      categoryId: "sub",
      amount: 149,
      note: "Spotify",
      date: `${month}-16`,
      accountId: "card",
      toAccountId: null,
    },
    {
      type: "expense",
      categoryId: "health",
      amount: 650,
      note: "藥局",
      date: `${month}-18`,
      accountId: "cash",
      toAccountId: null,
    },
    {
      type: "expense",
      categoryId: "food",
      amount: 740,
      note: "聚餐",
      date: `${month}-20`,
      accountId: "cash",
      toAccountId: null,
    },
    {
      type: "transfer",
      categoryId: "",
      amount: 3000,
      note: "提款",
      date: `${month}-21`,
      accountId: "bank",
      toAccountId: "cash",
    },
    {
      type: "expense",
      categoryId: "other-out",
      amount: 320,
      note: "雜支",
      date: `${month}-22`,
      accountId: "cash",
      toAccountId: null,
    },
    {
      type: "expense",
      categoryId: "food",
      amount: 390,
      note: "午餐",
      date: `${month}-24`,
      accountId: "cash",
      toAccountId: null,
    },
    {
      type: "expense",
      categoryId: "food",
      amount: 510,
      note: "晚餐",
      date: `${month}-25`,
      accountId: "cash",
      toAccountId: null,
    },
    {
      type: "expense",
      categoryId: "food",
      amount: 95,
      note: "早餐",
      date: `${month}-26`,
      accountId: "cash",
      toAccountId: null,
    },
    {
      type: "expense",
      categoryId: "food",
      amount: 168,
      note: "午餐",
      date: `${month}-26`,
      accountId: "cash",
      toAccountId: null,
    },
  ];

  return rows.map((row, i) => ({ ...row, id: id("tx", i + 1) }));
}
